/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.gms.dds.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.sdu.gms.dds.DeviceDefinitionRuntimeModule;
import dk.sdu.gms.dds.DeviceDefinitionStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DeviceDefinitionIdeSetup extends DeviceDefinitionStandaloneSetup {
  @Override
  public Injector createInjector() {
    DeviceDefinitionRuntimeModule _deviceDefinitionRuntimeModule = new DeviceDefinitionRuntimeModule();
    DeviceDefinitionIdeModule _deviceDefinitionIdeModule = new DeviceDefinitionIdeModule();
    return Guice.createInjector(Modules2.mixin(_deviceDefinitionRuntimeModule, _deviceDefinitionIdeModule));
  }
}
