package dk.sdu.gms.dds.generator;

import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class WebClientBoilerPlate {
  public static String generateCSS() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append(".chart-container {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("width: 600px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("height: auto;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("list-style-type: none;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border: 1px solid gray;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding: 5px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".flex-container {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("display: grid;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("grid-template-columns: repeat(auto-fit, minmax(600px, max-content));");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("grid-gap: 16px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("justify-content: center;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding: 32px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".centered {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("font-family: arial;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("font-size: 24px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("width: 100%;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".centered h3 {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("text-align: center;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".settings-table {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("width: 100%;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border-spacing: 16px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border-collapse: collapse;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".settings-table tr th input {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("width: 100px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".settings-table tr th h5 {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("width: 350px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("table tr {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border-top: 2px solid #EEE;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
  
  public static String generateHeader() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?php");
    _builder.newLine();
    _builder.newLine();
    _builder.append("$mqttHostServerSide = getenv(\"MQTT_HOST\");");
    _builder.newLine();
    _builder.append("$mqttHost = getenv(\"MQTT_CLIENT_SIDE\");");
    _builder.newLine();
    _builder.append("$username = getenv(\"MQTT_USERNAME\");");
    _builder.newLine();
    _builder.append("$password = getenv(\"MQTT_PASSWORD\");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("echo \"<script>\";");
    _builder.newLine();
    _builder.newLine();
    _builder.append("echo \"var MQTT_HOST = \\\"$mqttHost\\\"\\n\";");
    _builder.newLine();
    _builder.append("echo \"var MQTT_USERNAME = \\\"$username\\\"\\n\";");
    _builder.newLine();
    _builder.append("echo \"var MQTT_PASSWORD = \\\"$password\\\"\\n\";");
    _builder.newLine();
    _builder.newLine();
    _builder.append("echo \"</script>\";");
    _builder.newLine();
    _builder.append("?>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<!-- JQuery -->");
    _builder.newLine();
    _builder.append("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>");
    _builder.newLine();
    _builder.append("<script src=\"https://cdn.jsdelivr.net/npm/chart.js@3.6.0/dist/chart.min.js\"></script>");
    _builder.newLine();
    _builder.append("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js\" type=\"text/javascript\"></script>");
    _builder.newLine();
    _builder.append("<script src=/helper.js></script>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<!-- Latest compiled and minified CSS -->");
    _builder.newLine();
    _builder.append("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css\" integrity=\"sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu\" crossorigin=\"anonymous\">");
    _builder.newLine();
    _builder.append("<link rel=\"stylesheet\" href=\"/styles/chart.css\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<!-- Optional theme -->");
    _builder.newLine();
    _builder.append("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap-theme.min.css\" integrity=\"sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ\" crossorigin=\"anonymous\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<!-- Latest compiled and minified JavaScript -->");
    _builder.newLine();
    _builder.append("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js\" integrity=\"sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd\" crossorigin=\"anonymous\"></script>");
    _builder.newLine();
    _builder.newLine();
    return _builder.toString();
  }
  
  public static String generateBridge() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?php");
    _builder.newLine();
    _builder.newLine();
    _builder.append("$apiHost = getenv(\"API_HOST\");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("$type = $_GET[\'type\'];");
    _builder.newLine();
    _builder.append("$gateway = $_GET[\'gateway\'];");
    _builder.newLine();
    _builder.append("$worker = $_GET[\'worker\'];");
    _builder.newLine();
    _builder.append("$topic = $_GET[\'topic\'];");
    _builder.newLine();
    _builder.append("$from = $_GET[\'from\'];");
    _builder.newLine();
    _builder.append("$to = $_GET[\'to\'];");
    _builder.newLine();
    _builder.newLine();
    _builder.append("$queryArguments = \"$type/$gateway/$worker/$topic?from=$from&to=$to\";");
    _builder.newLine();
    _builder.newLine();
    _builder.append("if (!isset($apiHost)) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("$apiRoot = \"http://localhost:3000/$queryArguments\";");
    _builder.newLine();
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("$apiRoot = $apiHost . \"$queryArguments\";");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("$options = array(");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("\'http\' => array(");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("\'header\'  => \"Content-type: application/x-www-form-urlencoded\\r\\n\",");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("\'method\'  => \'GET\'");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("),");
    _builder.newLine();
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("$context  = stream_context_create($options);");
    _builder.newLine();
    _builder.append("$result = file_get_contents($apiRoot, false, $context);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("echo $result;");
    _builder.newLine();
    return _builder.toString();
  }
  
  public static String generateCommonBody() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<div class=\"navbar-default\" role=\"navigation\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"navbar-header\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<span class=\"sr-only\">links toggle button</span>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<span class=\"mdl-color--white white icon-bar\"></span>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<span class=\"mdl-color--white white icon-bar\"></span>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<span class=\"mdl-color--white icon-bar\"></span>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</button>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<a href=\"/\"><span class=\"navbar-brand\">Green House Management System</span></a>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"navbar-collapse collapse\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<ul class=\"nav navbar-nav\" style=\"float: right;\" id=\"navbar-categories\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    return _builder.toString();
  }
}
