/*
 * generated by Xtext 2.26.0
 */
package dk.gms.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class DeviceDefinitionIdeModule extends AbstractDeviceDefinitionIdeModule {
}
