/**
 * generated by Xtext 2.26.0
 */
package dk.gms.dsl.deviceDefinition;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Binding Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.gms.dsl.deviceDefinition.BindingRef#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see dk.gms.dsl.deviceDefinition.DeviceDefinitionPackage#getBindingRef()
 * @model
 * @generated
 */
public interface BindingRef extends Expression
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(Binding)
   * @see dk.gms.dsl.deviceDefinition.DeviceDefinitionPackage#getBindingRef_Ref()
   * @model
   * @generated
   */
  Binding getRef();

  /**
   * Sets the value of the '{@link dk.gms.dsl.deviceDefinition.BindingRef#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Binding value);

} // BindingRef
