/**
 * generated by Xtext 2.26.0
 */
package dk.gms.dsl.deviceDefinition;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hour</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.gms.dsl.deviceDefinition.DeviceDefinitionPackage#getHour()
 * @model
 * @generated
 */
public interface Hour extends TimeUnit
{
} // Hour
