/**
 * generated by Xtext 2.26.0
 */
package dk.gms.dsl.deviceDefinition;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Time Unit</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.gms.dsl.deviceDefinition.DeviceDefinitionPackage#getTimeUnit()
 * @model
 * @generated
 */
public interface TimeUnit extends EObject
{
} // TimeUnit
