/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.gms.dds.deviceDefinition;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean False</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getBooleanFalse()
 * @model
 * @generated
 */
public interface BooleanFalse extends Primitive
{
} // BooleanFalse
