/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.gms.dds.deviceDefinition;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gateway</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.Gateway#getName <em>Name</em>}</li>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.Gateway#getMac <em>Mac</em>}</li>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.Gateway#getChannel <em>Channel</em>}</li>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.Gateway#getErrorLed <em>Error Led</em>}</li>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.Gateway#getRetries <em>Retries</em>}</li>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.Gateway#getDelay <em>Delay</em>}</li>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.Gateway#getDelayTimeUnit <em>Delay Time Unit</em>}</li>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.Gateway#getWorkers <em>Workers</em>}</li>
 * </ul>
 *
 * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getGateway()
 * @model
 * @generated
 */
public interface Gateway extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getGateway_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link dk.sdu.gms.dds.deviceDefinition.Gateway#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Mac</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mac</em>' attribute.
   * @see #setMac(String)
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getGateway_Mac()
   * @model
   * @generated
   */
  String getMac();

  /**
   * Sets the value of the '{@link dk.sdu.gms.dds.deviceDefinition.Gateway#getMac <em>Mac</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mac</em>' attribute.
   * @see #getMac()
   * @generated
   */
  void setMac(String value);

  /**
   * Returns the value of the '<em><b>Channel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Channel</em>' attribute.
   * @see #setChannel(int)
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getGateway_Channel()
   * @model
   * @generated
   */
  int getChannel();

  /**
   * Sets the value of the '{@link dk.sdu.gms.dds.deviceDefinition.Gateway#getChannel <em>Channel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Channel</em>' attribute.
   * @see #getChannel()
   * @generated
   */
  void setChannel(int value);

  /**
   * Returns the value of the '<em><b>Error Led</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Error Led</em>' attribute list.
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getGateway_ErrorLed()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getErrorLed();

  /**
   * Returns the value of the '<em><b>Retries</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Retries</em>' attribute list.
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getGateway_Retries()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getRetries();

  /**
   * Returns the value of the '<em><b>Delay</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.gms.dds.deviceDefinition.NumberPrimitive}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delay</em>' containment reference list.
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getGateway_Delay()
   * @model containment="true"
   * @generated
   */
  EList<NumberPrimitive> getDelay();

  /**
   * Returns the value of the '<em><b>Delay Time Unit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delay Time Unit</em>' containment reference.
   * @see #setDelayTimeUnit(TimeUnit)
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getGateway_DelayTimeUnit()
   * @model containment="true"
   * @generated
   */
  TimeUnit getDelayTimeUnit();

  /**
   * Sets the value of the '{@link dk.sdu.gms.dds.deviceDefinition.Gateway#getDelayTimeUnit <em>Delay Time Unit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delay Time Unit</em>' containment reference.
   * @see #getDelayTimeUnit()
   * @generated
   */
  void setDelayTimeUnit(TimeUnit value);

  /**
   * Returns the value of the '<em><b>Workers</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.gms.dds.deviceDefinition.Worker}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Workers</em>' containment reference list.
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getGateway_Workers()
   * @model containment="true"
   * @generated
   */
  EList<Worker> getWorkers();

} // Gateway
