/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.gms.dds.deviceDefinition;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Generic Out</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getGenericOut()
 * @model
 * @generated
 */
public interface GenericOut extends PinType
{
} // GenericOut
