/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.gms.dds.deviceDefinition;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Internal Variable Use</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getInternalVariableUse()
 * @model
 * @generated
 */
public interface InternalVariableUse extends VariableUse
{
} // InternalVariableUse
