/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.gms.dds.deviceDefinition;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Minute</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getMinute()
 * @model
 * @generated
 */
public interface Minute extends TimeUnit
{
} // Minute
