/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.gms.dds.deviceDefinition;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.System#getName <em>Name</em>}</li>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.System#getWifiSsid <em>Wifi Ssid</em>}</li>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.System#getWifiPassword <em>Wifi Password</em>}</li>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.System#getMqttHost <em>Mqtt Host</em>}</li>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.System#getMqttUsername <em>Mqtt Username</em>}</li>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.System#getMqttPassword <em>Mqtt Password</em>}</li>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.System#getGateway <em>Gateway</em>}</li>
 *   <li>{@link dk.sdu.gms.dds.deviceDefinition.System#getGraphs <em>Graphs</em>}</li>
 * </ul>
 *
 * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getSystem()
 * @model
 * @generated
 */
public interface System extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getSystem_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link dk.sdu.gms.dds.deviceDefinition.System#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Wifi Ssid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wifi Ssid</em>' attribute.
   * @see #setWifiSsid(String)
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getSystem_WifiSsid()
   * @model
   * @generated
   */
  String getWifiSsid();

  /**
   * Sets the value of the '{@link dk.sdu.gms.dds.deviceDefinition.System#getWifiSsid <em>Wifi Ssid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wifi Ssid</em>' attribute.
   * @see #getWifiSsid()
   * @generated
   */
  void setWifiSsid(String value);

  /**
   * Returns the value of the '<em><b>Wifi Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wifi Password</em>' attribute.
   * @see #setWifiPassword(String)
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getSystem_WifiPassword()
   * @model
   * @generated
   */
  String getWifiPassword();

  /**
   * Sets the value of the '{@link dk.sdu.gms.dds.deviceDefinition.System#getWifiPassword <em>Wifi Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wifi Password</em>' attribute.
   * @see #getWifiPassword()
   * @generated
   */
  void setWifiPassword(String value);

  /**
   * Returns the value of the '<em><b>Mqtt Host</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mqtt Host</em>' attribute.
   * @see #setMqttHost(String)
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getSystem_MqttHost()
   * @model
   * @generated
   */
  String getMqttHost();

  /**
   * Sets the value of the '{@link dk.sdu.gms.dds.deviceDefinition.System#getMqttHost <em>Mqtt Host</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mqtt Host</em>' attribute.
   * @see #getMqttHost()
   * @generated
   */
  void setMqttHost(String value);

  /**
   * Returns the value of the '<em><b>Mqtt Username</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mqtt Username</em>' attribute.
   * @see #setMqttUsername(String)
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getSystem_MqttUsername()
   * @model
   * @generated
   */
  String getMqttUsername();

  /**
   * Sets the value of the '{@link dk.sdu.gms.dds.deviceDefinition.System#getMqttUsername <em>Mqtt Username</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mqtt Username</em>' attribute.
   * @see #getMqttUsername()
   * @generated
   */
  void setMqttUsername(String value);

  /**
   * Returns the value of the '<em><b>Mqtt Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mqtt Password</em>' attribute.
   * @see #setMqttPassword(String)
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getSystem_MqttPassword()
   * @model
   * @generated
   */
  String getMqttPassword();

  /**
   * Sets the value of the '{@link dk.sdu.gms.dds.deviceDefinition.System#getMqttPassword <em>Mqtt Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mqtt Password</em>' attribute.
   * @see #getMqttPassword()
   * @generated
   */
  void setMqttPassword(String value);

  /**
   * Returns the value of the '<em><b>Gateway</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gateway</em>' containment reference.
   * @see #setGateway(Gateway)
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getSystem_Gateway()
   * @model containment="true"
   * @generated
   */
  Gateway getGateway();

  /**
   * Sets the value of the '{@link dk.sdu.gms.dds.deviceDefinition.System#getGateway <em>Gateway</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gateway</em>' containment reference.
   * @see #getGateway()
   * @generated
   */
  void setGateway(Gateway value);

  /**
   * Returns the value of the '<em><b>Graphs</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.gms.dds.deviceDefinition.Graph}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Graphs</em>' containment reference list.
   * @see dk.sdu.gms.dds.deviceDefinition.DeviceDefinitionPackage#getSystem_Graphs()
   * @model containment="true"
   * @generated
   */
  EList<Graph> getGraphs();

} // System
