/*
 * generated by Xtext 2.26.0
 */
package dk.gms.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DeviceDefinitionUiModule extends AbstractDeviceDefinitionUiModule {

	public DeviceDefinitionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
