version: "3"
services:

  api:
    build: API/
    image: lomztein/gms-api:latest
    restart: always
    ports:
     - "3000:3010"
    networks:
     - frontend
     - backend
    depends_on:
     - mongo
     - mosquitto
    environment:
     - MQTT_HOST=mqtt://mosquitto:1883
     - MQTT_USERNAME=kristian
     - MQTT_PASSWORD=1234
     - MONGO_CONNECTION_STRING=mongodb://mongo:27017
     - MONGO_DATABASE=gms

  adapter:
    build: Adapter/
    image: lomztein/gms-adapter:latest
    restart: always
    depends_on:
     - mongo
     - mosquitto
    networks:
     - frontend
     - backend
    environment:
     - MQTT_HOST=mqtt://mosquitto:1883
     - MQTT_USERNAME=kristian
     - MQTT_PASSWORD=1234
     - MONGO_CONNECTION_STRING=mongodb://mongo:27017
     - MONGO_DATABASE=gms

  webclient:
    image: php:7.2-apache
    ports:
      - 3003:80
    volumes:
      - ./WebClient:/var/www/html
    restart: always
    depends_on:
     - mongo
     - mosquitto
     - api
    environment:
     - MQTT_HOST=mqtt://mosquitto:3002
     - MQTT_CLIENT_SIDE=mqtt://localhost:3002
     - MQTT_USERNAME=kristian
     - MQTT_PASSWORD=1234
     - API_HOST=http://api:3010
    networks:
     - frontend
     - backend
     
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
     - "3001:1883"
     - "3002:8081"
    networks:
     - frontend
    volumes:
     - ./mosquitto/:/mosquitto/

  mongo:
    build: MongoDB/
    image: lomztein/gms-mongo:latest
    restart: always
    container_name: mongo
    networks:
     - backend
    volumes:
     - database:/data/db
  
networks:

  frontend:
  
  backend:
  
volumes:

  database: