/**
 * generated by Xtext 2.26.0
 */
package dk.gms.dsl.deviceDefinition.impl;

import dk.gms.dsl.deviceDefinition.BooleanTrue;
import dk.gms.dsl.deviceDefinition.DeviceDefinitionPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Boolean True</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BooleanTrueImpl extends PrimitiveImpl implements BooleanTrue
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BooleanTrueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DeviceDefinitionPackage.Literals.BOOLEAN_TRUE;
  }

} //BooleanTrueImpl
