/**
 * generated by Xtext 2.25.0
 */
package dk.gms.dsl.deviceDefinition.impl;

import dk.gms.dsl.deviceDefinition.DeviceDefinitionPackage;
import dk.gms.dsl.deviceDefinition.Master;
import dk.gms.dsl.deviceDefinition.Slave;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Master</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dk.gms.dsl.deviceDefinition.impl.MasterImpl#getName <em>Name</em>}</li>
 *   <li>{@link dk.gms.dsl.deviceDefinition.impl.MasterImpl#getBluetoothName <em>Bluetooth Name</em>}</li>
 *   <li>{@link dk.gms.dsl.deviceDefinition.impl.MasterImpl#getSlaves <em>Slaves</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MasterImpl extends MinimalEObjectImpl.Container implements Master
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getBluetoothName() <em>Bluetooth Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBluetoothName()
   * @generated
   * @ordered
   */
  protected static final String BLUETOOTH_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBluetoothName() <em>Bluetooth Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBluetoothName()
   * @generated
   * @ordered
   */
  protected String bluetoothName = BLUETOOTH_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getSlaves() <em>Slaves</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSlaves()
   * @generated
   * @ordered
   */
  protected EList<Slave> slaves;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MasterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DeviceDefinitionPackage.Literals.MASTER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DeviceDefinitionPackage.MASTER__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getBluetoothName()
  {
    return bluetoothName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBluetoothName(String newBluetoothName)
  {
    String oldBluetoothName = bluetoothName;
    bluetoothName = newBluetoothName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DeviceDefinitionPackage.MASTER__BLUETOOTH_NAME, oldBluetoothName, bluetoothName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Slave> getSlaves()
  {
    if (slaves == null)
    {
      slaves = new EObjectContainmentEList<Slave>(Slave.class, this, DeviceDefinitionPackage.MASTER__SLAVES);
    }
    return slaves;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DeviceDefinitionPackage.MASTER__SLAVES:
        return ((InternalEList<?>)getSlaves()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DeviceDefinitionPackage.MASTER__NAME:
        return getName();
      case DeviceDefinitionPackage.MASTER__BLUETOOTH_NAME:
        return getBluetoothName();
      case DeviceDefinitionPackage.MASTER__SLAVES:
        return getSlaves();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DeviceDefinitionPackage.MASTER__NAME:
        setName((String)newValue);
        return;
      case DeviceDefinitionPackage.MASTER__BLUETOOTH_NAME:
        setBluetoothName((String)newValue);
        return;
      case DeviceDefinitionPackage.MASTER__SLAVES:
        getSlaves().clear();
        getSlaves().addAll((Collection<? extends Slave>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DeviceDefinitionPackage.MASTER__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DeviceDefinitionPackage.MASTER__BLUETOOTH_NAME:
        setBluetoothName(BLUETOOTH_NAME_EDEFAULT);
        return;
      case DeviceDefinitionPackage.MASTER__SLAVES:
        getSlaves().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DeviceDefinitionPackage.MASTER__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DeviceDefinitionPackage.MASTER__BLUETOOTH_NAME:
        return BLUETOOTH_NAME_EDEFAULT == null ? bluetoothName != null : !BLUETOOTH_NAME_EDEFAULT.equals(bluetoothName);
      case DeviceDefinitionPackage.MASTER__SLAVES:
        return slaves != null && !slaves.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", bluetoothName: ");
    result.append(bluetoothName);
    result.append(')');
    return result.toString();
  }

} //MasterImpl
