/*
 * generated by Xtext 2.26.0
 */
package dk.sdu.gms.dds.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DeviceDefinitionGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class SystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.System");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cImportsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cImportsImportParserRuleCall_0_0 = (RuleCall)cImportsAssignment_0.eContents().get(0);
		private final Keyword cSystemKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cGatewayAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cGatewayGatewayParserRuleCall_3_0 = (RuleCall)cGatewayAssignment_3.eContents().get(0);
		private final Assignment cGraphsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cGraphsGraphParserRuleCall_4_0 = (RuleCall)cGraphsAssignment_4.eContents().get(0);
		
		//System:
		//    (imports += Import)*
		//    'System' ':'
		//    gateway = Gateway
		//    graphs += Graph*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(imports += Import)*
		//'System' ':'
		//gateway = Gateway
		//graphs += Graph*
		public Group getGroup() { return cGroup; }
		
		//(imports += Import)*
		public Assignment getImportsAssignment_0() { return cImportsAssignment_0; }
		
		//Import
		public RuleCall getImportsImportParserRuleCall_0_0() { return cImportsImportParserRuleCall_0_0; }
		
		//'System'
		public Keyword getSystemKeyword_1() { return cSystemKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//gateway = Gateway
		public Assignment getGatewayAssignment_3() { return cGatewayAssignment_3; }
		
		//Gateway
		public RuleCall getGatewayGatewayParserRuleCall_3_0() { return cGatewayGatewayParserRuleCall_3_0; }
		
		//graphs += Graph*
		public Assignment getGraphsAssignment_4() { return cGraphsAssignment_4; }
		
		//Graph
		public RuleCall getGraphsGraphParserRuleCall_4_0() { return cGraphsGraphParserRuleCall_4_0; }
	}
	public class GraphElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Graph");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGraphKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cTypeImportCrossReference_1_0 = (CrossReference)cTypeAssignment_1.eContents().get(0);
		private final RuleCall cTypeImportIDTerminalRuleCall_1_0_1 = (RuleCall)cTypeImportCrossReference_1_0.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cCategoryKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cCategoryAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cCategorySTRINGTerminalRuleCall_5_0 = (RuleCall)cCategoryAssignment_5.eContents().get(0);
		private final Keyword cTitleKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTitleAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTitleSTRINGTerminalRuleCall_7_0 = (RuleCall)cTitleAssignment_7.eContents().get(0);
		private final Keyword cXKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cXlabelAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cXlabelSTRINGTerminalRuleCall_9_0 = (RuleCall)cXlabelAssignment_9.eContents().get(0);
		private final Keyword cYKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cYlabelAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cYlabelSTRINGTerminalRuleCall_11_0 = (RuleCall)cYlabelAssignment_11.eContents().get(0);
		
		//Graph:
		//    'Graph' type = [Import] name=ID ':'
		//    'category' category = STRING
		//    'title' title = STRING
		//    'x' xlabel = STRING
		//    'y' ylabel = STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Graph' type = [Import] name=ID ':'
		//'category' category = STRING
		//'title' title = STRING
		//'x' xlabel = STRING
		//'y' ylabel = STRING
		public Group getGroup() { return cGroup; }
		
		//'Graph'
		public Keyword getGraphKeyword_0() { return cGraphKeyword_0; }
		
		//type = [Import]
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//[Import]
		public CrossReference getTypeImportCrossReference_1_0() { return cTypeImportCrossReference_1_0; }
		
		//ID
		public RuleCall getTypeImportIDTerminalRuleCall_1_0_1() { return cTypeImportIDTerminalRuleCall_1_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//'category'
		public Keyword getCategoryKeyword_4() { return cCategoryKeyword_4; }
		
		//category = STRING
		public Assignment getCategoryAssignment_5() { return cCategoryAssignment_5; }
		
		//STRING
		public RuleCall getCategorySTRINGTerminalRuleCall_5_0() { return cCategorySTRINGTerminalRuleCall_5_0; }
		
		//'title'
		public Keyword getTitleKeyword_6() { return cTitleKeyword_6; }
		
		//title = STRING
		public Assignment getTitleAssignment_7() { return cTitleAssignment_7; }
		
		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_7_0() { return cTitleSTRINGTerminalRuleCall_7_0; }
		
		//'x'
		public Keyword getXKeyword_8() { return cXKeyword_8; }
		
		//xlabel = STRING
		public Assignment getXlabelAssignment_9() { return cXlabelAssignment_9; }
		
		//STRING
		public RuleCall getXlabelSTRINGTerminalRuleCall_9_0() { return cXlabelSTRINGTerminalRuleCall_9_0; }
		
		//'y'
		public Keyword getYKeyword_10() { return cYKeyword_10; }
		
		//ylabel = STRING
		public Assignment getYlabelAssignment_11() { return cYlabelAssignment_11; }
		
		//STRING
		public RuleCall getYlabelSTRINGTerminalRuleCall_11_0() { return cYlabelSTRINGTerminalRuleCall_11_0; }
	}
	public class GatewayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Gateway");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGatewayKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMacKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMacAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMacMACTerminalRuleCall_4_0 = (RuleCall)cMacAssignment_4.eContents().get(0);
		private final Assignment cWorkersAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cWorkersWorkerParserRuleCall_5_0 = (RuleCall)cWorkersAssignment_5.eContents().get(0);
		
		//Gateway:
		//    'Gateway' name=ID ':'
		//    'mac' mac = MAC
		//    workers += Worker+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Gateway' name=ID ':'
		//'mac' mac = MAC
		//workers += Worker+
		public Group getGroup() { return cGroup; }
		
		//'Gateway'
		public Keyword getGatewayKeyword_0() { return cGatewayKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//'mac'
		public Keyword getMacKeyword_3() { return cMacKeyword_3; }
		
		//mac = MAC
		public Assignment getMacAssignment_4() { return cMacAssignment_4; }
		
		//MAC
		public RuleCall getMacMACTerminalRuleCall_4_0() { return cMacMACTerminalRuleCall_4_0; }
		
		//workers += Worker+
		public Assignment getWorkersAssignment_5() { return cWorkersAssignment_5; }
		
		//Worker
		public RuleCall getWorkersWorkerParserRuleCall_5_0() { return cWorkersWorkerParserRuleCall_5_0; }
	}
	public class WorkerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Worker");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWorkerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMacKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMacAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMacMACTerminalRuleCall_4_0 = (RuleCall)cMacAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cSleepKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cForKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cSleepTimeAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cSleepTimeINTTerminalRuleCall_5_2_0 = (RuleCall)cSleepTimeAssignment_5_2.eContents().get(0);
		private final Assignment cTimeUnitAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cTimeUnitTimeUnitParserRuleCall_5_3_0 = (RuleCall)cTimeUnitAssignment_5_3.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cBroadcastKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cForKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cBroadcastTimeAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cBroadcastTimeINTTerminalRuleCall_6_2_0 = (RuleCall)cBroadcastTimeAssignment_6_2.eContents().get(0);
		private final Assignment cTimeUnitAssignment_6_3 = (Assignment)cGroup_6.eContents().get(3);
		private final RuleCall cTimeUnitTimeUnitParserRuleCall_6_3_0 = (RuleCall)cTimeUnitAssignment_6_3.eContents().get(0);
		private final Assignment cDevicesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cDevicesDeviceParserRuleCall_7_0 = (RuleCall)cDevicesAssignment_7.eContents().get(0);
		
		//Worker:
		//    'Worker' name=ID ':'
		//    'mac' mac = MAC
		//    ('sleep' 'for' sleepTime = INT timeUnit += TimeUnit)?
		//    ('broadcast' 'for' broadcastTime = INT timeUnit += TimeUnit)?
		//    devices += Device*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Worker' name=ID ':'
		//'mac' mac = MAC
		//('sleep' 'for' sleepTime = INT timeUnit += TimeUnit)?
		//('broadcast' 'for' broadcastTime = INT timeUnit += TimeUnit)?
		//devices += Device*
		public Group getGroup() { return cGroup; }
		
		//'Worker'
		public Keyword getWorkerKeyword_0() { return cWorkerKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//'mac'
		public Keyword getMacKeyword_3() { return cMacKeyword_3; }
		
		//mac = MAC
		public Assignment getMacAssignment_4() { return cMacAssignment_4; }
		
		//MAC
		public RuleCall getMacMACTerminalRuleCall_4_0() { return cMacMACTerminalRuleCall_4_0; }
		
		//('sleep' 'for' sleepTime = INT timeUnit += TimeUnit)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'sleep'
		public Keyword getSleepKeyword_5_0() { return cSleepKeyword_5_0; }
		
		//'for'
		public Keyword getForKeyword_5_1() { return cForKeyword_5_1; }
		
		//sleepTime = INT
		public Assignment getSleepTimeAssignment_5_2() { return cSleepTimeAssignment_5_2; }
		
		//INT
		public RuleCall getSleepTimeINTTerminalRuleCall_5_2_0() { return cSleepTimeINTTerminalRuleCall_5_2_0; }
		
		//timeUnit += TimeUnit
		public Assignment getTimeUnitAssignment_5_3() { return cTimeUnitAssignment_5_3; }
		
		//TimeUnit
		public RuleCall getTimeUnitTimeUnitParserRuleCall_5_3_0() { return cTimeUnitTimeUnitParserRuleCall_5_3_0; }
		
		//('broadcast' 'for' broadcastTime = INT timeUnit += TimeUnit)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'broadcast'
		public Keyword getBroadcastKeyword_6_0() { return cBroadcastKeyword_6_0; }
		
		//'for'
		public Keyword getForKeyword_6_1() { return cForKeyword_6_1; }
		
		//broadcastTime = INT
		public Assignment getBroadcastTimeAssignment_6_2() { return cBroadcastTimeAssignment_6_2; }
		
		//INT
		public RuleCall getBroadcastTimeINTTerminalRuleCall_6_2_0() { return cBroadcastTimeINTTerminalRuleCall_6_2_0; }
		
		//timeUnit += TimeUnit
		public Assignment getTimeUnitAssignment_6_3() { return cTimeUnitAssignment_6_3; }
		
		//TimeUnit
		public RuleCall getTimeUnitTimeUnitParserRuleCall_6_3_0() { return cTimeUnitTimeUnitParserRuleCall_6_3_0; }
		
		//devices += Device*
		public Assignment getDevicesAssignment_7() { return cDevicesAssignment_7; }
		
		//Device
		public RuleCall getDevicesDeviceParserRuleCall_7_0() { return cDevicesDeviceParserRuleCall_7_0; }
	}
	public class DeviceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Device");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSensorParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cActuatorParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Device:
		//    Sensor | Actuator
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Sensor | Actuator
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Sensor
		public RuleCall getSensorParserRuleCall_0() { return cSensorParserRuleCall_0; }
		
		//Actuator
		public RuleCall getActuatorParserRuleCall_1() { return cActuatorParserRuleCall_1; }
	}
	public class SensorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Sensor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSensorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cTypeImportCrossReference_1_0 = (CrossReference)cTypeAssignment_1.eContents().get(0);
		private final RuleCall cTypeImportIDTerminalRuleCall_1_0_1 = (RuleCall)cTypeImportCrossReference_1_0.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cPinsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPinsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPinsINTTerminalRuleCall_5_0 = (RuleCall)cPinsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPinsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPinsINTTerminalRuleCall_6_1_0 = (RuleCall)cPinsAssignment_6_1.eContents().get(0);
		private final Keyword cRateKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cSampleRateAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cSampleRatePrimitiveParserRuleCall_8_0 = (RuleCall)cSampleRateAssignment_8.eContents().get(0);
		private final Assignment cOutputsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cOutputsSensorOutputParserRuleCall_9_0 = (RuleCall)cOutputsAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cBehaviorKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cBehaviorAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cBehaviorSampleBehaviorParserRuleCall_10_1_0 = (RuleCall)cBehaviorAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cSampleKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cIfKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cPredicateAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cPredicateExpParserRuleCall_11_2_0 = (RuleCall)cPredicateAssignment_11_2.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cGraphKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cGraphAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final CrossReference cGraphGraphCrossReference_12_1_0 = (CrossReference)cGraphAssignment_12_1.eContents().get(0);
		private final RuleCall cGraphGraphIDTerminalRuleCall_12_1_0_1 = (RuleCall)cGraphGraphCrossReference_12_1_0.eContents().get(1);
		
		//Sensor:
		//    'Sensor' type = [Import] (name=ID)? ':'
		//    'pins' pins += INT* (',' pins += INT)*
		//    'rate' sampleRate = Primitive
		//    (outputs += SensorOutput)*
		//    ('behavior' behavior += SampleBehavior)?
		//    ('sample' 'if' predicate += Exp)?
		//    ('graph' graph = [Graph])?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Sensor' type = [Import] (name=ID)? ':'
		//'pins' pins += INT* (',' pins += INT)*
		//'rate' sampleRate = Primitive
		//(outputs += SensorOutput)*
		//('behavior' behavior += SampleBehavior)?
		//('sample' 'if' predicate += Exp)?
		//('graph' graph = [Graph])?
		public Group getGroup() { return cGroup; }
		
		//'Sensor'
		public Keyword getSensorKeyword_0() { return cSensorKeyword_0; }
		
		//type = [Import]
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//[Import]
		public CrossReference getTypeImportCrossReference_1_0() { return cTypeImportCrossReference_1_0; }
		
		//ID
		public RuleCall getTypeImportIDTerminalRuleCall_1_0_1() { return cTypeImportIDTerminalRuleCall_1_0_1; }
		
		//(name=ID)?
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//'pins'
		public Keyword getPinsKeyword_4() { return cPinsKeyword_4; }
		
		//pins += INT*
		public Assignment getPinsAssignment_5() { return cPinsAssignment_5; }
		
		//INT
		public RuleCall getPinsINTTerminalRuleCall_5_0() { return cPinsINTTerminalRuleCall_5_0; }
		
		//(',' pins += INT)*
		public Group getGroup_6() { return cGroup_6; }
		
		//','
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//pins += INT
		public Assignment getPinsAssignment_6_1() { return cPinsAssignment_6_1; }
		
		//INT
		public RuleCall getPinsINTTerminalRuleCall_6_1_0() { return cPinsINTTerminalRuleCall_6_1_0; }
		
		//'rate'
		public Keyword getRateKeyword_7() { return cRateKeyword_7; }
		
		//sampleRate = Primitive
		public Assignment getSampleRateAssignment_8() { return cSampleRateAssignment_8; }
		
		//Primitive
		public RuleCall getSampleRatePrimitiveParserRuleCall_8_0() { return cSampleRatePrimitiveParserRuleCall_8_0; }
		
		//(outputs += SensorOutput)*
		public Assignment getOutputsAssignment_9() { return cOutputsAssignment_9; }
		
		//SensorOutput
		public RuleCall getOutputsSensorOutputParserRuleCall_9_0() { return cOutputsSensorOutputParserRuleCall_9_0; }
		
		//('behavior' behavior += SampleBehavior)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'behavior'
		public Keyword getBehaviorKeyword_10_0() { return cBehaviorKeyword_10_0; }
		
		//behavior += SampleBehavior
		public Assignment getBehaviorAssignment_10_1() { return cBehaviorAssignment_10_1; }
		
		//SampleBehavior
		public RuleCall getBehaviorSampleBehaviorParserRuleCall_10_1_0() { return cBehaviorSampleBehaviorParserRuleCall_10_1_0; }
		
		//('sample' 'if' predicate += Exp)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'sample'
		public Keyword getSampleKeyword_11_0() { return cSampleKeyword_11_0; }
		
		//'if'
		public Keyword getIfKeyword_11_1() { return cIfKeyword_11_1; }
		
		//predicate += Exp
		public Assignment getPredicateAssignment_11_2() { return cPredicateAssignment_11_2; }
		
		//Exp
		public RuleCall getPredicateExpParserRuleCall_11_2_0() { return cPredicateExpParserRuleCall_11_2_0; }
		
		//('graph' graph = [Graph])?
		public Group getGroup_12() { return cGroup_12; }
		
		//'graph'
		public Keyword getGraphKeyword_12_0() { return cGraphKeyword_12_0; }
		
		//graph = [Graph]
		public Assignment getGraphAssignment_12_1() { return cGraphAssignment_12_1; }
		
		//[Graph]
		public CrossReference getGraphGraphCrossReference_12_1_0() { return cGraphGraphCrossReference_12_1_0; }
		
		//ID
		public RuleCall getGraphGraphIDTerminalRuleCall_12_1_0_1() { return cGraphGraphIDTerminalRuleCall_12_1_0_1; }
	}
	public class SampleBehaviorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.SampleBehavior");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cTypeImportCrossReference_0_0 = (CrossReference)cTypeAssignment_0.eContents().get(0);
		private final RuleCall cTypeImportIDTerminalRuleCall_0_0_1 = (RuleCall)cTypeImportCrossReference_0_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cArgsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cArgsPrimaryParserRuleCall_2_0 = (RuleCall)cArgsAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPinsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPinsPrimaryParserRuleCall_3_1_0 = (RuleCall)cPinsAssignment_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SampleBehavior:
		//    type = [Import] '(' args += Primary* (',' pins += Primary)* ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//type = [Import] '(' args += Primary* (',' pins += Primary)* ')'
		public Group getGroup() { return cGroup; }
		
		//type = [Import]
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//[Import]
		public CrossReference getTypeImportCrossReference_0_0() { return cTypeImportCrossReference_0_0; }
		
		//ID
		public RuleCall getTypeImportIDTerminalRuleCall_0_0_1() { return cTypeImportIDTerminalRuleCall_0_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//args += Primary*
		public Assignment getArgsAssignment_2() { return cArgsAssignment_2; }
		
		//Primary
		public RuleCall getArgsPrimaryParserRuleCall_2_0() { return cArgsPrimaryParserRuleCall_2_0; }
		
		//(',' pins += Primary)*
		public Group getGroup_3() { return cGroup_3; }
		
		//','
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//pins += Primary
		public Assignment getPinsAssignment_3_1() { return cPinsAssignment_3_1; }
		
		//Primary
		public RuleCall getPinsPrimaryParserRuleCall_3_1_0() { return cPinsPrimaryParserRuleCall_3_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class TimeUnitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.TimeUnit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cSecondAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Alternatives cAlternatives_0_1 = (Alternatives)cGroup_0.eContents().get(1);
		private final Keyword cSecondKeyword_0_1_0 = (Keyword)cAlternatives_0_1.eContents().get(0);
		private final Keyword cSecondsKeyword_0_1_1 = (Keyword)cAlternatives_0_1.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cMinuteAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Alternatives cAlternatives_1_1 = (Alternatives)cGroup_1.eContents().get(1);
		private final Keyword cMinuteKeyword_1_1_0 = (Keyword)cAlternatives_1_1.eContents().get(0);
		private final Keyword cMinutesKeyword_1_1_1 = (Keyword)cAlternatives_1_1.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cHourAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Alternatives cAlternatives_2_1 = (Alternatives)cGroup_2.eContents().get(1);
		private final Keyword cHourKeyword_2_1_0 = (Keyword)cAlternatives_2_1.eContents().get(0);
		private final Keyword cHoursKeyword_2_1_1 = (Keyword)cAlternatives_2_1.eContents().get(1);
		
		//TimeUnit:
		//    {Second} ('second'|'seconds') | {Minute} ('minute'|'minutes') | {Hour} ('hour'|'hours')
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Second} ('second'|'seconds') | {Minute} ('minute'|'minutes') | {Hour} ('hour'|'hours')
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{Second} ('second'|'seconds')
		public Group getGroup_0() { return cGroup_0; }
		
		//{Second}
		public Action getSecondAction_0_0() { return cSecondAction_0_0; }
		
		//('second'|'seconds')
		public Alternatives getAlternatives_0_1() { return cAlternatives_0_1; }
		
		//'second'
		public Keyword getSecondKeyword_0_1_0() { return cSecondKeyword_0_1_0; }
		
		//'seconds'
		public Keyword getSecondsKeyword_0_1_1() { return cSecondsKeyword_0_1_1; }
		
		//{Minute} ('minute'|'minutes')
		public Group getGroup_1() { return cGroup_1; }
		
		//{Minute}
		public Action getMinuteAction_1_0() { return cMinuteAction_1_0; }
		
		//('minute'|'minutes')
		public Alternatives getAlternatives_1_1() { return cAlternatives_1_1; }
		
		//'minute'
		public Keyword getMinuteKeyword_1_1_0() { return cMinuteKeyword_1_1_0; }
		
		//'minutes'
		public Keyword getMinutesKeyword_1_1_1() { return cMinutesKeyword_1_1_1; }
		
		//{Hour} ('hour'|'hours')
		public Group getGroup_2() { return cGroup_2; }
		
		//{Hour}
		public Action getHourAction_2_0() { return cHourAction_2_0; }
		
		//('hour'|'hours')
		public Alternatives getAlternatives_2_1() { return cAlternatives_2_1; }
		
		//'hour'
		public Keyword getHourKeyword_2_1_0() { return cHourKeyword_2_1_0; }
		
		//'hours'
		public Keyword getHoursKeyword_2_1_1() { return cHoursKeyword_2_1_1; }
	}
	public class BindingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Binding");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSensorOutputParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSettingParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Binding:
		//    SensorOutput | Setting
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//SensorOutput | Setting
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SensorOutput
		public RuleCall getSensorOutputParserRuleCall_0() { return cSensorOutputParserRuleCall_0; }
		
		//Setting
		public RuleCall getSettingParserRuleCall_1() { return cSettingParserRuleCall_1; }
	}
	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Import:
		//    'import' name=ID
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'import' name=ID
		public Group getGroup() { return cGroup; }
		
		//'import'
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class SensorOutputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.SensorOutput");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOutKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOutputAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cOutputSTRINGTerminalRuleCall_1_0 = (RuleCall)cOutputAssignment_1.eContents().get(0);
		private final Keyword cAsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cWithKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cMappingKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cMappingAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cMappingExpParserRuleCall_4_2_0 = (RuleCall)cMappingAssignment_4_2.eContents().get(0);
		
		//SensorOutput:
		//    'out' (output=STRING)? 'as' name=ID ('with' 'mapping' mapping = Exp)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'out' (output=STRING)? 'as' name=ID ('with' 'mapping' mapping = Exp)?
		public Group getGroup() { return cGroup; }
		
		//'out'
		public Keyword getOutKeyword_0() { return cOutKeyword_0; }
		
		//(output=STRING)?
		public Assignment getOutputAssignment_1() { return cOutputAssignment_1; }
		
		//STRING
		public RuleCall getOutputSTRINGTerminalRuleCall_1_0() { return cOutputSTRINGTerminalRuleCall_1_0; }
		
		//'as'
		public Keyword getAsKeyword_2() { return cAsKeyword_2; }
		
		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }
		
		//('with' 'mapping' mapping = Exp)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'with'
		public Keyword getWithKeyword_4_0() { return cWithKeyword_4_0; }
		
		//'mapping'
		public Keyword getMappingKeyword_4_1() { return cMappingKeyword_4_1; }
		
		//mapping = Exp
		public Assignment getMappingAssignment_4_2() { return cMappingAssignment_4_2; }
		
		//Exp
		public RuleCall getMappingExpParserRuleCall_4_2_0() { return cMappingExpParserRuleCall_4_2_0; }
	}
	public class ActuatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Actuator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActuatorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cTypeImportCrossReference_1_0 = (CrossReference)cTypeAssignment_1.eContents().get(0);
		private final RuleCall cTypeImportIDTerminalRuleCall_1_0_1 = (RuleCall)cTypeImportCrossReference_1_0.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cPinsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPinsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPinsINTTerminalRuleCall_5_0 = (RuleCall)cPinsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPinsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPinsINTTerminalRuleCall_6_1_0 = (RuleCall)cPinsAssignment_6_1.eContents().get(0);
		private final Assignment cSettingsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cSettingsSettingParserRuleCall_7_0 = (RuleCall)cSettingsAssignment_7.eContents().get(0);
		private final Assignment cTriggerAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTriggerTriggerParserRuleCall_8_0 = (RuleCall)cTriggerAssignment_8.eContents().get(0);
		
		//Actuator:
		//    'Actuator' type = [Import] (name=ID)? ':'
		//    'pins' pins += INT* (',' pins += INT)*
		//    settings += Setting*
		//    trigger = Trigger
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Actuator' type = [Import] (name=ID)? ':'
		//'pins' pins += INT* (',' pins += INT)*
		//settings += Setting*
		//trigger = Trigger
		public Group getGroup() { return cGroup; }
		
		//'Actuator'
		public Keyword getActuatorKeyword_0() { return cActuatorKeyword_0; }
		
		//type = [Import]
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//[Import]
		public CrossReference getTypeImportCrossReference_1_0() { return cTypeImportCrossReference_1_0; }
		
		//ID
		public RuleCall getTypeImportIDTerminalRuleCall_1_0_1() { return cTypeImportIDTerminalRuleCall_1_0_1; }
		
		//(name=ID)?
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//'pins'
		public Keyword getPinsKeyword_4() { return cPinsKeyword_4; }
		
		//pins += INT*
		public Assignment getPinsAssignment_5() { return cPinsAssignment_5; }
		
		//INT
		public RuleCall getPinsINTTerminalRuleCall_5_0() { return cPinsINTTerminalRuleCall_5_0; }
		
		//(',' pins += INT)*
		public Group getGroup_6() { return cGroup_6; }
		
		//','
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//pins += INT
		public Assignment getPinsAssignment_6_1() { return cPinsAssignment_6_1; }
		
		//INT
		public RuleCall getPinsINTTerminalRuleCall_6_1_0() { return cPinsINTTerminalRuleCall_6_1_0; }
		
		//settings += Setting*
		public Assignment getSettingsAssignment_7() { return cSettingsAssignment_7; }
		
		//Setting
		public RuleCall getSettingsSettingParserRuleCall_7_0() { return cSettingsSettingParserRuleCall_7_0; }
		
		//trigger = Trigger
		public Assignment getTriggerAssignment_8() { return cTriggerAssignment_8; }
		
		//Trigger
		public RuleCall getTriggerTriggerParserRuleCall_8_0() { return cTriggerTriggerParserRuleCall_8_0; }
	}
	public class TriggerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Trigger");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cWhenAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cWhenKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cExpAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cExpExpParserRuleCall_0_2_0 = (RuleCall)cExpAssignment_0_2.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cOnOffAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cOnKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cOnExpAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cOnExpExpParserRuleCall_1_2_0 = (RuleCall)cOnExpAssignment_1_2.eContents().get(0);
		private final Alternatives cAlternatives_1_3 = (Alternatives)cGroup_1.eContents().get(3);
		private final Group cGroup_1_3_0 = (Group)cAlternatives_1_3.eContents().get(0);
		private final Keyword cOffKeyword_1_3_0_0 = (Keyword)cGroup_1_3_0.eContents().get(0);
		private final Assignment cOffExpAssignment_1_3_0_1 = (Assignment)cGroup_1_3_0.eContents().get(1);
		private final RuleCall cOffExpExpParserRuleCall_1_3_0_1_0 = (RuleCall)cOffExpAssignment_1_3_0_1.eContents().get(0);
		private final Group cGroup_1_3_1 = (Group)cAlternatives_1_3.eContents().get(1);
		private final Keyword cRunKeyword_1_3_1_0 = (Keyword)cGroup_1_3_1.eContents().get(0);
		private final Keyword cForKeyword_1_3_1_1 = (Keyword)cGroup_1_3_1.eContents().get(1);
		private final Assignment cTimeAssignment_1_3_1_2 = (Assignment)cGroup_1_3_1.eContents().get(2);
		private final RuleCall cTimeINTTerminalRuleCall_1_3_1_2_0 = (RuleCall)cTimeAssignment_1_3_1_2.eContents().get(0);
		private final Assignment cUnitAssignment_1_3_1_3 = (Assignment)cGroup_1_3_1.eContents().get(3);
		private final RuleCall cUnitTimeUnitParserRuleCall_1_3_1_3_0 = (RuleCall)cUnitAssignment_1_3_1_3.eContents().get(0);
		
		//Trigger:
		//    {When} 'when' exp = Exp
		//     | {OnOff} 'on' onExp = Exp (('off' offExp = Exp) | ('run' 'for' time=INT unit=TimeUnit))
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{When} 'when' exp = Exp
		// | {OnOff} 'on' onExp = Exp (('off' offExp = Exp) | ('run' 'for' time=INT unit=TimeUnit))
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{When} 'when' exp = Exp
		public Group getGroup_0() { return cGroup_0; }
		
		//{When}
		public Action getWhenAction_0_0() { return cWhenAction_0_0; }
		
		//'when'
		public Keyword getWhenKeyword_0_1() { return cWhenKeyword_0_1; }
		
		//exp = Exp
		public Assignment getExpAssignment_0_2() { return cExpAssignment_0_2; }
		
		//Exp
		public RuleCall getExpExpParserRuleCall_0_2_0() { return cExpExpParserRuleCall_0_2_0; }
		
		//{OnOff} 'on' onExp = Exp (('off' offExp = Exp) | ('run' 'for' time=INT unit=TimeUnit))
		public Group getGroup_1() { return cGroup_1; }
		
		//{OnOff}
		public Action getOnOffAction_1_0() { return cOnOffAction_1_0; }
		
		//'on'
		public Keyword getOnKeyword_1_1() { return cOnKeyword_1_1; }
		
		//onExp = Exp
		public Assignment getOnExpAssignment_1_2() { return cOnExpAssignment_1_2; }
		
		//Exp
		public RuleCall getOnExpExpParserRuleCall_1_2_0() { return cOnExpExpParserRuleCall_1_2_0; }
		
		//(('off' offExp = Exp) | ('run' 'for' time=INT unit=TimeUnit))
		public Alternatives getAlternatives_1_3() { return cAlternatives_1_3; }
		
		//('off' offExp = Exp)
		public Group getGroup_1_3_0() { return cGroup_1_3_0; }
		
		//'off'
		public Keyword getOffKeyword_1_3_0_0() { return cOffKeyword_1_3_0_0; }
		
		//offExp = Exp
		public Assignment getOffExpAssignment_1_3_0_1() { return cOffExpAssignment_1_3_0_1; }
		
		//Exp
		public RuleCall getOffExpExpParserRuleCall_1_3_0_1_0() { return cOffExpExpParserRuleCall_1_3_0_1_0; }
		
		//('run' 'for' time=INT unit=TimeUnit)
		public Group getGroup_1_3_1() { return cGroup_1_3_1; }
		
		//'run'
		public Keyword getRunKeyword_1_3_1_0() { return cRunKeyword_1_3_1_0; }
		
		//'for'
		public Keyword getForKeyword_1_3_1_1() { return cForKeyword_1_3_1_1; }
		
		//time=INT
		public Assignment getTimeAssignment_1_3_1_2() { return cTimeAssignment_1_3_1_2; }
		
		//INT
		public RuleCall getTimeINTTerminalRuleCall_1_3_1_2_0() { return cTimeINTTerminalRuleCall_1_3_1_2_0; }
		
		//unit=TimeUnit
		public Assignment getUnitAssignment_1_3_1_3() { return cUnitAssignment_1_3_1_3; }
		
		//TimeUnit
		public RuleCall getUnitTimeUnitParserRuleCall_1_3_1_3_0() { return cUnitTimeUnitParserRuleCall_1_3_1_3_0; }
	}
	public class SettingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Setting");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSettingKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValuePrimitiveParserRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		
		//Setting:
		//    'setting' name=ID '=' value=Primitive
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'setting' name=ID '=' value=Primitive
		public Group getGroup() { return cGroup; }
		
		//'setting'
		public Keyword getSettingKeyword_0() { return cSettingKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//value=Primitive
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//Primitive
		public RuleCall getValuePrimitiveParserRuleCall_3_0() { return cValuePrimitiveParserRuleCall_3_0; }
	}
	public class PrimitiveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Primitive");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cDecimalPrimitiveAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cValueAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cValueDECIMALTerminalRuleCall_0_1_0 = (RuleCall)cValueAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cIntPrimitiveAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cValueAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_1_1_0 = (RuleCall)cValueAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cBooleanTrueAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Keyword cTRUEKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cBooleanFalseAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Keyword cFALSEKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		
		//Primitive:
		//    {DecimalPrimitive} value = DECIMAL | {IntPrimitive} value=INT | {BooleanTrue} 'TRUE' | {BooleanFalse} 'FALSE'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{DecimalPrimitive} value = DECIMAL | {IntPrimitive} value=INT | {BooleanTrue} 'TRUE' | {BooleanFalse} 'FALSE'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{DecimalPrimitive} value = DECIMAL
		public Group getGroup_0() { return cGroup_0; }
		
		//{DecimalPrimitive}
		public Action getDecimalPrimitiveAction_0_0() { return cDecimalPrimitiveAction_0_0; }
		
		//value = DECIMAL
		public Assignment getValueAssignment_0_1() { return cValueAssignment_0_1; }
		
		//DECIMAL
		public RuleCall getValueDECIMALTerminalRuleCall_0_1_0() { return cValueDECIMALTerminalRuleCall_0_1_0; }
		
		//{IntPrimitive} value=INT
		public Group getGroup_1() { return cGroup_1; }
		
		//{IntPrimitive}
		public Action getIntPrimitiveAction_1_0() { return cIntPrimitiveAction_1_0; }
		
		//value=INT
		public Assignment getValueAssignment_1_1() { return cValueAssignment_1_1; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_1_1_0() { return cValueINTTerminalRuleCall_1_1_0; }
		
		//{BooleanTrue} 'TRUE'
		public Group getGroup_2() { return cGroup_2; }
		
		//{BooleanTrue}
		public Action getBooleanTrueAction_2_0() { return cBooleanTrueAction_2_0; }
		
		//'TRUE'
		public Keyword getTRUEKeyword_2_1() { return cTRUEKeyword_2_1; }
		
		//{BooleanFalse} 'FALSE'
		public Group getGroup_3() { return cGroup_3; }
		
		//{BooleanFalse}
		public Action getBooleanFalseAction_3_0() { return cBooleanFalseAction_3_0; }
		
		//'FALSE'
		public Keyword getFALSEKeyword_3_1() { return cFALSEKeyword_3_1; }
	}
	public class ExpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Exp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cFactorParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Action cPlusLeftAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Keyword cPlusSignKeyword_1_0_0_1 = (Keyword)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Action cMinusLeftAction_1_0_1_0 = (Action)cGroup_1_0_1.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1_0_1_1 = (Keyword)cGroup_1_0_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightFactorParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//Exp returns Expression:
		//    Factor (( {Plus.left=current} '+' | {Minus.left=current}  '-' ) right=Factor)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Factor (( {Plus.left=current} '+' | {Minus.left=current}  '-' ) right=Factor)*
		public Group getGroup() { return cGroup; }
		
		//Factor
		public RuleCall getFactorParserRuleCall_0() { return cFactorParserRuleCall_0; }
		
		//(( {Plus.left=current} '+' | {Minus.left=current}  '-' ) right=Factor)*
		public Group getGroup_1() { return cGroup_1; }
		
		//( {Plus.left=current} '+' | {Minus.left=current}  '-' )
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//{Plus.left=current} '+'
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//{Plus.left=current}
		public Action getPlusLeftAction_1_0_0_0() { return cPlusLeftAction_1_0_0_0; }
		
		//'+'
		public Keyword getPlusSignKeyword_1_0_0_1() { return cPlusSignKeyword_1_0_0_1; }
		
		//{Minus.left=current}  '-'
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//{Minus.left=current}
		public Action getMinusLeftAction_1_0_1_0() { return cMinusLeftAction_1_0_1_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1_0_1_1() { return cHyphenMinusKeyword_1_0_1_1; }
		
		//right=Factor
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//Factor
		public RuleCall getRightFactorParserRuleCall_1_1_0() { return cRightFactorParserRuleCall_1_1_0; }
	}
	public class FactorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Factor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cCompareParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Action cMultLeftAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Keyword cAsteriskKeyword_1_0_0_1 = (Keyword)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Action cDivLeftAction_1_0_1_0 = (Action)cGroup_1_0_1.eContents().get(0);
		private final Keyword cSolidusKeyword_1_0_1_1 = (Keyword)cGroup_1_0_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightCompareParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//Factor returns Expression:
		//    Compare (({Mult.left=current} '*' | {Div.left=current}  '/'  ) right=Compare)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Compare (({Mult.left=current} '*' | {Div.left=current}  '/'  ) right=Compare)*
		public Group getGroup() { return cGroup; }
		
		//Compare
		public RuleCall getCompareParserRuleCall_0() { return cCompareParserRuleCall_0; }
		
		//(({Mult.left=current} '*' | {Div.left=current}  '/'  ) right=Compare)*
		public Group getGroup_1() { return cGroup_1; }
		
		//({Mult.left=current} '*' | {Div.left=current}  '/'  )
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//{Mult.left=current} '*'
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//{Mult.left=current}
		public Action getMultLeftAction_1_0_0_0() { return cMultLeftAction_1_0_0_0; }
		
		//'*'
		public Keyword getAsteriskKeyword_1_0_0_1() { return cAsteriskKeyword_1_0_0_1; }
		
		//{Div.left=current}  '/'
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//{Div.left=current}
		public Action getDivLeftAction_1_0_1_0() { return cDivLeftAction_1_0_1_0; }
		
		//'/'
		public Keyword getSolidusKeyword_1_0_1_1() { return cSolidusKeyword_1_0_1_1; }
		
		//right=Compare
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//Compare
		public RuleCall getRightCompareParserRuleCall_1_1_0() { return cRightCompareParserRuleCall_1_1_0; }
	}
	public class CompareElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Compare");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cCompareOrEqualsParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Action cGreaterLeftAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_1_0_0_1 = (Keyword)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Action cLesserLeftAction_1_0_1_0 = (Action)cGroup_1_0_1.eContents().get(0);
		private final Keyword cLessThanSignKeyword_1_0_1_1 = (Keyword)cGroup_1_0_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightCompareOrEqualsParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//Compare returns Expression:
		//    CompareOrEquals (( {Greater.left=current} '>' | {Lesser.left=current}  '<' ) right=CompareOrEquals)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//CompareOrEquals (( {Greater.left=current} '>' | {Lesser.left=current}  '<' ) right=CompareOrEquals)*
		public Group getGroup() { return cGroup; }
		
		//CompareOrEquals
		public RuleCall getCompareOrEqualsParserRuleCall_0() { return cCompareOrEqualsParserRuleCall_0; }
		
		//(( {Greater.left=current} '>' | {Lesser.left=current}  '<' ) right=CompareOrEquals)*
		public Group getGroup_1() { return cGroup_1; }
		
		//( {Greater.left=current} '>' | {Lesser.left=current}  '<' )
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//{Greater.left=current} '>'
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//{Greater.left=current}
		public Action getGreaterLeftAction_1_0_0_0() { return cGreaterLeftAction_1_0_0_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_1_0_0_1() { return cGreaterThanSignKeyword_1_0_0_1; }
		
		//{Lesser.left=current}  '<'
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//{Lesser.left=current}
		public Action getLesserLeftAction_1_0_1_0() { return cLesserLeftAction_1_0_1_0; }
		
		//'<'
		public Keyword getLessThanSignKeyword_1_0_1_1() { return cLessThanSignKeyword_1_0_1_1; }
		
		//right=CompareOrEquals
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//CompareOrEquals
		public RuleCall getRightCompareOrEqualsParserRuleCall_1_1_0() { return cRightCompareOrEqualsParserRuleCall_1_1_0; }
	}
	public class CompareOrEqualsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.CompareOrEquals");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cEqualsOrNotEqualsParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Action cGreaterOrEqualsLeftAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Keyword cGreaterThanSignEqualsSignKeyword_1_0_0_1 = (Keyword)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Action cLesserOrEqualsLeftAction_1_0_1_0 = (Action)cGroup_1_0_1.eContents().get(0);
		private final Keyword cLessThanSignEqualsSignKeyword_1_0_1_1 = (Keyword)cGroup_1_0_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightEqualsOrNotEqualsParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//CompareOrEquals returns Expression:
		//    EqualsOrNotEquals (({GreaterOrEquals.left=current} '>=' | {LesserOrEquals.left=current}  '<=' ) right=EqualsOrNotEquals)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//EqualsOrNotEquals (({GreaterOrEquals.left=current} '>=' | {LesserOrEquals.left=current}  '<=' ) right=EqualsOrNotEquals)*
		public Group getGroup() { return cGroup; }
		
		//EqualsOrNotEquals
		public RuleCall getEqualsOrNotEqualsParserRuleCall_0() { return cEqualsOrNotEqualsParserRuleCall_0; }
		
		//(({GreaterOrEquals.left=current} '>=' | {LesserOrEquals.left=current}  '<=' ) right=EqualsOrNotEquals)*
		public Group getGroup_1() { return cGroup_1; }
		
		//({GreaterOrEquals.left=current} '>=' | {LesserOrEquals.left=current}  '<=' )
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//{GreaterOrEquals.left=current} '>='
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//{GreaterOrEquals.left=current}
		public Action getGreaterOrEqualsLeftAction_1_0_0_0() { return cGreaterOrEqualsLeftAction_1_0_0_0; }
		
		//'>='
		public Keyword getGreaterThanSignEqualsSignKeyword_1_0_0_1() { return cGreaterThanSignEqualsSignKeyword_1_0_0_1; }
		
		//{LesserOrEquals.left=current}  '<='
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//{LesserOrEquals.left=current}
		public Action getLesserOrEqualsLeftAction_1_0_1_0() { return cLesserOrEqualsLeftAction_1_0_1_0; }
		
		//'<='
		public Keyword getLessThanSignEqualsSignKeyword_1_0_1_1() { return cLessThanSignEqualsSignKeyword_1_0_1_1; }
		
		//right=EqualsOrNotEquals
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//EqualsOrNotEquals
		public RuleCall getRightEqualsOrNotEqualsParserRuleCall_1_1_0() { return cRightEqualsOrNotEqualsParserRuleCall_1_1_0; }
	}
	public class EqualsOrNotEqualsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.EqualsOrNotEquals");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAndOrParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Action cEqualsLeftAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Keyword cEqualsSignEqualsSignKeyword_1_0_0_1 = (Keyword)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Action cNotEqualsLeftAction_1_0_1_0 = (Action)cGroup_1_0_1.eContents().get(0);
		private final Keyword cExclamationMarkEqualsSignKeyword_1_0_1_1 = (Keyword)cGroup_1_0_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightAndOrParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//EqualsOrNotEquals returns Expression:
		//    AndOr (({Equals.left=current} '==' | {NotEquals.left=current}  '!=' ) right=AndOr)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//AndOr (({Equals.left=current} '==' | {NotEquals.left=current}  '!=' ) right=AndOr)*
		public Group getGroup() { return cGroup; }
		
		//AndOr
		public RuleCall getAndOrParserRuleCall_0() { return cAndOrParserRuleCall_0; }
		
		//(({Equals.left=current} '==' | {NotEquals.left=current}  '!=' ) right=AndOr)*
		public Group getGroup_1() { return cGroup_1; }
		
		//({Equals.left=current} '==' | {NotEquals.left=current}  '!=' )
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//{Equals.left=current} '=='
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//{Equals.left=current}
		public Action getEqualsLeftAction_1_0_0_0() { return cEqualsLeftAction_1_0_0_0; }
		
		//'=='
		public Keyword getEqualsSignEqualsSignKeyword_1_0_0_1() { return cEqualsSignEqualsSignKeyword_1_0_0_1; }
		
		//{NotEquals.left=current}  '!='
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//{NotEquals.left=current}
		public Action getNotEqualsLeftAction_1_0_1_0() { return cNotEqualsLeftAction_1_0_1_0; }
		
		//'!='
		public Keyword getExclamationMarkEqualsSignKeyword_1_0_1_1() { return cExclamationMarkEqualsSignKeyword_1_0_1_1; }
		
		//right=AndOr
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//AndOr
		public RuleCall getRightAndOrParserRuleCall_1_1_0() { return cRightAndOrParserRuleCall_1_1_0; }
	}
	public class AndOrElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.AndOr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimaryParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Action cAndLeftAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Keyword cAndKeyword_1_0_0_1 = (Keyword)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Action cOrLeftAction_1_0_1_0 = (Action)cGroup_1_0_1.eContents().get(0);
		private final Keyword cOrKeyword_1_0_1_1 = (Keyword)cGroup_1_0_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightPrimaryParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//AndOr returns Expression:
		//    Primary (({And.left=current} 'and' | {Or.left=current}  'or' ) right=Primary)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Primary (({And.left=current} 'and' | {Or.left=current}  'or' ) right=Primary)*
		public Group getGroup() { return cGroup; }
		
		//Primary
		public RuleCall getPrimaryParserRuleCall_0() { return cPrimaryParserRuleCall_0; }
		
		//(({And.left=current} 'and' | {Or.left=current}  'or' ) right=Primary)*
		public Group getGroup_1() { return cGroup_1; }
		
		//({And.left=current} 'and' | {Or.left=current}  'or' )
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//{And.left=current} 'and'
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//{And.left=current}
		public Action getAndLeftAction_1_0_0_0() { return cAndLeftAction_1_0_0_0; }
		
		//'and'
		public Keyword getAndKeyword_1_0_0_1() { return cAndKeyword_1_0_0_1; }
		
		//{Or.left=current}  'or'
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//{Or.left=current}
		public Action getOrLeftAction_1_0_1_0() { return cOrLeftAction_1_0_1_0; }
		
		//'or'
		public Keyword getOrKeyword_1_0_1_1() { return cOrKeyword_1_0_1_1; }
		
		//right=Primary
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//Primary
		public RuleCall getRightPrimaryParserRuleCall_1_1_0() { return cRightPrimaryParserRuleCall_1_1_0; }
	}
	public class PrimaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Primary");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPrimitiveParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cParenthesisParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cVariableUseParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cExternalCallParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Action cValueAction_4_0 = (Action)cGroup_4.eContents().get(0);
		private final Keyword cValueKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		
		//Primary returns Expression:
		//     Primitive | Parenthesis | VariableUse | ExternalCall | {Value} 'value'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Primitive | Parenthesis | VariableUse | ExternalCall | {Value} 'value'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Primitive
		public RuleCall getPrimitiveParserRuleCall_0() { return cPrimitiveParserRuleCall_0; }
		
		//Parenthesis
		public RuleCall getParenthesisParserRuleCall_1() { return cParenthesisParserRuleCall_1; }
		
		//VariableUse
		public RuleCall getVariableUseParserRuleCall_2() { return cVariableUseParserRuleCall_2; }
		
		//ExternalCall
		public RuleCall getExternalCallParserRuleCall_3() { return cExternalCallParserRuleCall_3; }
		
		//{Value} 'value'
		public Group getGroup_4() { return cGroup_4; }
		
		//{Value}
		public Action getValueAction_4_0() { return cValueAction_4_0; }
		
		//'value'
		public Keyword getValueKeyword_4_1() { return cValueKeyword_4_1; }
	}
	public class ExternalCallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.ExternalCall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCallKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cFuncAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cFuncImportCrossReference_1_0 = (CrossReference)cFuncAssignment_1.eContents().get(0);
		private final RuleCall cFuncImportIDTerminalRuleCall_1_0_1 = (RuleCall)cFuncImportCrossReference_1_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cArgsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cArgsExpParserRuleCall_3_0 = (RuleCall)cArgsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cArgsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cArgsExpParserRuleCall_4_1_0 = (RuleCall)cArgsAssignment_4_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ExternalCall:
		//    'call' func = [Import] '(' args += Exp? (',' args += Exp)* ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'call' func = [Import] '(' args += Exp? (',' args += Exp)* ')'
		public Group getGroup() { return cGroup; }
		
		//'call'
		public Keyword getCallKeyword_0() { return cCallKeyword_0; }
		
		//func = [Import]
		public Assignment getFuncAssignment_1() { return cFuncAssignment_1; }
		
		//[Import]
		public CrossReference getFuncImportCrossReference_1_0() { return cFuncImportCrossReference_1_0; }
		
		//ID
		public RuleCall getFuncImportIDTerminalRuleCall_1_0_1() { return cFuncImportIDTerminalRuleCall_1_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//args += Exp?
		public Assignment getArgsAssignment_3() { return cArgsAssignment_3; }
		
		//Exp
		public RuleCall getArgsExpParserRuleCall_3_0() { return cArgsExpParserRuleCall_3_0; }
		
		//(',' args += Exp)*
		public Group getGroup_4() { return cGroup_4; }
		
		//','
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//args += Exp
		public Assignment getArgsAssignment_4_1() { return cArgsAssignment_4_1; }
		
		//Exp
		public RuleCall getArgsExpParserRuleCall_4_1_0() { return cArgsExpParserRuleCall_4_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class InternalVariableUseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.InternalVariableUse");
		private final Assignment cRefAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cRefBindingCrossReference_0 = (CrossReference)cRefAssignment.eContents().get(0);
		private final RuleCall cRefBindingIDTerminalRuleCall_0_1 = (RuleCall)cRefBindingCrossReference_0.eContents().get(1);
		
		//InternalVariableUse:
		//    ref = [Binding]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//ref = [Binding]
		public Assignment getRefAssignment() { return cRefAssignment; }
		
		//[Binding]
		public CrossReference getRefBindingCrossReference_0() { return cRefBindingCrossReference_0; }
		
		//ID
		public RuleCall getRefBindingIDTerminalRuleCall_0_1() { return cRefBindingIDTerminalRuleCall_0_1; }
	}
	public class ExternalVariableUseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.ExternalVariableUse");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cObjAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cObjDeviceCrossReference_0_0 = (CrossReference)cObjAssignment_0.eContents().get(0);
		private final RuleCall cObjDeviceIDTerminalRuleCall_0_0_1 = (RuleCall)cObjDeviceCrossReference_0_0.eContents().get(1);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cRefAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cRefBindingCrossReference_2_0 = (CrossReference)cRefAssignment_2.eContents().get(0);
		private final RuleCall cRefBindingIDTerminalRuleCall_2_0_1 = (RuleCall)cRefBindingCrossReference_2_0.eContents().get(1);
		
		//ExternalVariableUse:
		//    obj = [Device] ('.'|'->') ref = [Binding]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//obj = [Device] ('.'|'->') ref = [Binding]
		public Group getGroup() { return cGroup; }
		
		//obj = [Device]
		public Assignment getObjAssignment_0() { return cObjAssignment_0; }
		
		//[Device]
		public CrossReference getObjDeviceCrossReference_0_0() { return cObjDeviceCrossReference_0_0; }
		
		//ID
		public RuleCall getObjDeviceIDTerminalRuleCall_0_0_1() { return cObjDeviceIDTerminalRuleCall_0_0_1; }
		
		//('.'|'->')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_1_1() { return cHyphenMinusGreaterThanSignKeyword_1_1; }
		
		//ref = [Binding]
		public Assignment getRefAssignment_2() { return cRefAssignment_2; }
		
		//[Binding]
		public CrossReference getRefBindingCrossReference_2_0() { return cRefBindingCrossReference_2_0; }
		
		//ID
		public RuleCall getRefBindingIDTerminalRuleCall_2_0_1() { return cRefBindingIDTerminalRuleCall_2_0_1; }
	}
	public class VariableUseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.VariableUse");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cInternalVariableUseParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cExternalVariableUseParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//VariableUse:
		//    InternalVariableUse | ExternalVariableUse
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//InternalVariableUse | ExternalVariableUse
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//InternalVariableUse
		public RuleCall getInternalVariableUseParserRuleCall_0() { return cInternalVariableUseParserRuleCall_0; }
		
		//ExternalVariableUse
		public RuleCall getExternalVariableUseParserRuleCall_1() { return cExternalVariableUseParserRuleCall_1; }
	}
	public class ParenthesisElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.Parenthesis");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cExpAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExpExpParserRuleCall_1_0 = (RuleCall)cExpAssignment_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Parenthesis:
		//    '(' exp=Exp ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'(' exp=Exp ')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//exp=Exp
		public Assignment getExpAssignment_1() { return cExpAssignment_1; }
		
		//Exp
		public RuleCall getExpExpParserRuleCall_1_0() { return cExpExpParserRuleCall_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}
	
	
	private final SystemElements pSystem;
	private final GraphElements pGraph;
	private final GatewayElements pGateway;
	private final WorkerElements pWorker;
	private final DeviceElements pDevice;
	private final TerminalRule tMAC;
	private final TerminalRule tHEXBYTE;
	private final SensorElements pSensor;
	private final SampleBehaviorElements pSampleBehavior;
	private final TimeUnitElements pTimeUnit;
	private final BindingElements pBinding;
	private final ImportElements pImport;
	private final SensorOutputElements pSensorOutput;
	private final ActuatorElements pActuator;
	private final TriggerElements pTrigger;
	private final SettingElements pSetting;
	private final TerminalRule tDECIMAL;
	private final PrimitiveElements pPrimitive;
	private final ExpElements pExp;
	private final FactorElements pFactor;
	private final CompareElements pCompare;
	private final CompareOrEqualsElements pCompareOrEquals;
	private final EqualsOrNotEqualsElements pEqualsOrNotEquals;
	private final AndOrElements pAndOr;
	private final PrimaryElements pPrimary;
	private final ExternalCallElements pExternalCall;
	private final InternalVariableUseElements pInternalVariableUse;
	private final ExternalVariableUseElements pExternalVariableUse;
	private final VariableUseElements pVariableUse;
	private final ParenthesisElements pParenthesis;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DeviceDefinitionGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSystem = new SystemElements();
		this.pGraph = new GraphElements();
		this.pGateway = new GatewayElements();
		this.pWorker = new WorkerElements();
		this.pDevice = new DeviceElements();
		this.tMAC = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.MAC");
		this.tHEXBYTE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.HEXBYTE");
		this.pSensor = new SensorElements();
		this.pSampleBehavior = new SampleBehaviorElements();
		this.pTimeUnit = new TimeUnitElements();
		this.pBinding = new BindingElements();
		this.pImport = new ImportElements();
		this.pSensorOutput = new SensorOutputElements();
		this.pActuator = new ActuatorElements();
		this.pTrigger = new TriggerElements();
		this.pSetting = new SettingElements();
		this.tDECIMAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "dk.sdu.gms.dds.DeviceDefinition.DECIMAL");
		this.pPrimitive = new PrimitiveElements();
		this.pExp = new ExpElements();
		this.pFactor = new FactorElements();
		this.pCompare = new CompareElements();
		this.pCompareOrEquals = new CompareOrEqualsElements();
		this.pEqualsOrNotEquals = new EqualsOrNotEqualsElements();
		this.pAndOr = new AndOrElements();
		this.pPrimary = new PrimaryElements();
		this.pExternalCall = new ExternalCallElements();
		this.pInternalVariableUse = new InternalVariableUseElements();
		this.pExternalVariableUse = new ExternalVariableUseElements();
		this.pVariableUse = new VariableUseElements();
		this.pParenthesis = new ParenthesisElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("dk.sdu.gms.dds.DeviceDefinition".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//System:
	//    (imports += Import)*
	//    'System' ':'
	//    gateway = Gateway
	//    graphs += Graph*
	//;
	public SystemElements getSystemAccess() {
		return pSystem;
	}
	
	public ParserRule getSystemRule() {
		return getSystemAccess().getRule();
	}
	
	//Graph:
	//    'Graph' type = [Import] name=ID ':'
	//    'category' category = STRING
	//    'title' title = STRING
	//    'x' xlabel = STRING
	//    'y' ylabel = STRING
	//;
	public GraphElements getGraphAccess() {
		return pGraph;
	}
	
	public ParserRule getGraphRule() {
		return getGraphAccess().getRule();
	}
	
	//Gateway:
	//    'Gateway' name=ID ':'
	//    'mac' mac = MAC
	//    workers += Worker+
	//;
	public GatewayElements getGatewayAccess() {
		return pGateway;
	}
	
	public ParserRule getGatewayRule() {
		return getGatewayAccess().getRule();
	}
	
	//Worker:
	//    'Worker' name=ID ':'
	//    'mac' mac = MAC
	//    ('sleep' 'for' sleepTime = INT timeUnit += TimeUnit)?
	//    ('broadcast' 'for' broadcastTime = INT timeUnit += TimeUnit)?
	//    devices += Device*
	//;
	public WorkerElements getWorkerAccess() {
		return pWorker;
	}
	
	public ParserRule getWorkerRule() {
		return getWorkerAccess().getRule();
	}
	
	//Device:
	//    Sensor | Actuator
	//;
	public DeviceElements getDeviceAccess() {
		return pDevice;
	}
	
	public ParserRule getDeviceRule() {
		return getDeviceAccess().getRule();
	}
	
	//terminal MAC:
	//    HEXBYTE ('-'|':') HEXBYTE ('-'|':') HEXBYTE ('-'|':') HEXBYTE ('-'|':') HEXBYTE ('-'|':') HEXBYTE
	//;
	public TerminalRule getMACRule() {
		return tMAC;
	}
	
	//terminal fragment HEXBYTE:
	//    ('0'..'9'|'A'..'F')('0'..'9'|'A'..'F')
	//;
	public TerminalRule getHEXBYTERule() {
		return tHEXBYTE;
	}
	
	//Sensor:
	//    'Sensor' type = [Import] (name=ID)? ':'
	//    'pins' pins += INT* (',' pins += INT)*
	//    'rate' sampleRate = Primitive
	//    (outputs += SensorOutput)*
	//    ('behavior' behavior += SampleBehavior)?
	//    ('sample' 'if' predicate += Exp)?
	//    ('graph' graph = [Graph])?
	//;
	public SensorElements getSensorAccess() {
		return pSensor;
	}
	
	public ParserRule getSensorRule() {
		return getSensorAccess().getRule();
	}
	
	//SampleBehavior:
	//    type = [Import] '(' args += Primary* (',' pins += Primary)* ')'
	//;
	public SampleBehaviorElements getSampleBehaviorAccess() {
		return pSampleBehavior;
	}
	
	public ParserRule getSampleBehaviorRule() {
		return getSampleBehaviorAccess().getRule();
	}
	
	//TimeUnit:
	//    {Second} ('second'|'seconds') | {Minute} ('minute'|'minutes') | {Hour} ('hour'|'hours')
	//;
	public TimeUnitElements getTimeUnitAccess() {
		return pTimeUnit;
	}
	
	public ParserRule getTimeUnitRule() {
		return getTimeUnitAccess().getRule();
	}
	
	//Binding:
	//    SensorOutput | Setting
	//;
	public BindingElements getBindingAccess() {
		return pBinding;
	}
	
	public ParserRule getBindingRule() {
		return getBindingAccess().getRule();
	}
	
	//Import:
	//    'import' name=ID
	//;
	public ImportElements getImportAccess() {
		return pImport;
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}
	
	//SensorOutput:
	//    'out' (output=STRING)? 'as' name=ID ('with' 'mapping' mapping = Exp)?
	//;
	public SensorOutputElements getSensorOutputAccess() {
		return pSensorOutput;
	}
	
	public ParserRule getSensorOutputRule() {
		return getSensorOutputAccess().getRule();
	}
	
	//Actuator:
	//    'Actuator' type = [Import] (name=ID)? ':'
	//    'pins' pins += INT* (',' pins += INT)*
	//    settings += Setting*
	//    trigger = Trigger
	//;
	public ActuatorElements getActuatorAccess() {
		return pActuator;
	}
	
	public ParserRule getActuatorRule() {
		return getActuatorAccess().getRule();
	}
	
	//Trigger:
	//    {When} 'when' exp = Exp
	//     | {OnOff} 'on' onExp = Exp (('off' offExp = Exp) | ('run' 'for' time=INT unit=TimeUnit))
	//;
	public TriggerElements getTriggerAccess() {
		return pTrigger;
	}
	
	public ParserRule getTriggerRule() {
		return getTriggerAccess().getRule();
	}
	
	//Setting:
	//    'setting' name=ID '=' value=Primitive
	//;
	public SettingElements getSettingAccess() {
		return pSetting;
	}
	
	public ParserRule getSettingRule() {
		return getSettingAccess().getRule();
	}
	
	//terminal DECIMAL:
	//    '-'? INT ('.' INT)+
	//;
	public TerminalRule getDECIMALRule() {
		return tDECIMAL;
	}
	
	//Primitive:
	//    {DecimalPrimitive} value = DECIMAL | {IntPrimitive} value=INT | {BooleanTrue} 'TRUE' | {BooleanFalse} 'FALSE'
	//;
	public PrimitiveElements getPrimitiveAccess() {
		return pPrimitive;
	}
	
	public ParserRule getPrimitiveRule() {
		return getPrimitiveAccess().getRule();
	}
	
	//Exp returns Expression:
	//    Factor (( {Plus.left=current} '+' | {Minus.left=current}  '-' ) right=Factor)*
	//;
	public ExpElements getExpAccess() {
		return pExp;
	}
	
	public ParserRule getExpRule() {
		return getExpAccess().getRule();
	}
	
	//Factor returns Expression:
	//    Compare (({Mult.left=current} '*' | {Div.left=current}  '/'  ) right=Compare)*
	//;
	public FactorElements getFactorAccess() {
		return pFactor;
	}
	
	public ParserRule getFactorRule() {
		return getFactorAccess().getRule();
	}
	
	//Compare returns Expression:
	//    CompareOrEquals (( {Greater.left=current} '>' | {Lesser.left=current}  '<' ) right=CompareOrEquals)*
	//;
	public CompareElements getCompareAccess() {
		return pCompare;
	}
	
	public ParserRule getCompareRule() {
		return getCompareAccess().getRule();
	}
	
	//CompareOrEquals returns Expression:
	//    EqualsOrNotEquals (({GreaterOrEquals.left=current} '>=' | {LesserOrEquals.left=current}  '<=' ) right=EqualsOrNotEquals)*
	//;
	public CompareOrEqualsElements getCompareOrEqualsAccess() {
		return pCompareOrEquals;
	}
	
	public ParserRule getCompareOrEqualsRule() {
		return getCompareOrEqualsAccess().getRule();
	}
	
	//EqualsOrNotEquals returns Expression:
	//    AndOr (({Equals.left=current} '==' | {NotEquals.left=current}  '!=' ) right=AndOr)*
	//;
	public EqualsOrNotEqualsElements getEqualsOrNotEqualsAccess() {
		return pEqualsOrNotEquals;
	}
	
	public ParserRule getEqualsOrNotEqualsRule() {
		return getEqualsOrNotEqualsAccess().getRule();
	}
	
	//AndOr returns Expression:
	//    Primary (({And.left=current} 'and' | {Or.left=current}  'or' ) right=Primary)*
	//;
	public AndOrElements getAndOrAccess() {
		return pAndOr;
	}
	
	public ParserRule getAndOrRule() {
		return getAndOrAccess().getRule();
	}
	
	//Primary returns Expression:
	//     Primitive | Parenthesis | VariableUse | ExternalCall | {Value} 'value'
	//;
	public PrimaryElements getPrimaryAccess() {
		return pPrimary;
	}
	
	public ParserRule getPrimaryRule() {
		return getPrimaryAccess().getRule();
	}
	
	//ExternalCall:
	//    'call' func = [Import] '(' args += Exp? (',' args += Exp)* ')'
	//;
	public ExternalCallElements getExternalCallAccess() {
		return pExternalCall;
	}
	
	public ParserRule getExternalCallRule() {
		return getExternalCallAccess().getRule();
	}
	
	//InternalVariableUse:
	//    ref = [Binding]
	//;
	public InternalVariableUseElements getInternalVariableUseAccess() {
		return pInternalVariableUse;
	}
	
	public ParserRule getInternalVariableUseRule() {
		return getInternalVariableUseAccess().getRule();
	}
	
	//ExternalVariableUse:
	//    obj = [Device] ('.'|'->') ref = [Binding]
	//;
	public ExternalVariableUseElements getExternalVariableUseAccess() {
		return pExternalVariableUse;
	}
	
	public ParserRule getExternalVariableUseRule() {
		return getExternalVariableUseAccess().getRule();
	}
	
	//VariableUse:
	//    InternalVariableUse | ExternalVariableUse
	//;
	public VariableUseElements getVariableUseAccess() {
		return pVariableUse;
	}
	
	public ParserRule getVariableUseRule() {
		return getVariableUseAccess().getRule();
	}
	
	//Parenthesis:
	//    '(' exp=Exp ')'
	//;
	public ParenthesisElements getParenthesisAccess() {
		return pParenthesis;
	}
	
	public ParserRule getParenthesisRule() {
		return getParenthesisAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
