/**
 * generated by Xtext 2.25.0
 */
package dk.gms.dsl.deviceDefinition;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.gms.dsl.deviceDefinition.Sensor#getType <em>Type</em>}</li>
 *   <li>{@link dk.gms.dsl.deviceDefinition.Sensor#getPins <em>Pins</em>}</li>
 *   <li>{@link dk.gms.dsl.deviceDefinition.Sensor#getGraph <em>Graph</em>}</li>
 * </ul>
 *
 * @see dk.gms.dsl.deviceDefinition.DeviceDefinitionPackage#getSensor()
 * @model
 * @generated
 */
public interface Sensor extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link dk.gms.dsl.deviceDefinition.SensorType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see dk.gms.dsl.deviceDefinition.SensorType
   * @see #setType(SensorType)
   * @see dk.gms.dsl.deviceDefinition.DeviceDefinitionPackage#getSensor_Type()
   * @model
   * @generated
   */
  SensorType getType();

  /**
   * Sets the value of the '{@link dk.gms.dsl.deviceDefinition.Sensor#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see dk.gms.dsl.deviceDefinition.SensorType
   * @see #getType()
   * @generated
   */
  void setType(SensorType value);

  /**
   * Returns the value of the '<em><b>Pins</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pins</em>' attribute list.
   * @see dk.gms.dsl.deviceDefinition.DeviceDefinitionPackage#getSensor_Pins()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getPins();

  /**
   * Returns the value of the '<em><b>Graph</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Graph</em>' reference.
   * @see #setGraph(Graph)
   * @see dk.gms.dsl.deviceDefinition.DeviceDefinitionPackage#getSensor_Graph()
   * @model
   * @generated
   */
  Graph getGraph();

  /**
   * Sets the value of the '{@link dk.gms.dsl.deviceDefinition.Sensor#getGraph <em>Graph</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Graph</em>' reference.
   * @see #getGraph()
   * @generated
   */
  void setGraph(Graph value);

} // Sensor
